Repository SOPT-HONEY-WEB-CODING-TEST-CONCEPT/CodeTestPractice, pull requests merged in 2023-11, with the labels that each got.

#3 [week 1] 주간 결산_이시연
  시연/week1/BiggestNum.js
  시연/week1/KthNum.js
Labels: 1주차, 정렬

#1 [week 1] 주간 결산_이정우
  정우/week1/K번째수.js
  정우/week1/가장 큰 수.js
Labels: 1주차, 정렬

#7 [week 2] 주간 결산_이시연
  .github/PULL-REQUEST-TEMPLATE.md
  시연/week1/.gitkeep
  시연/week2/기능개발.js
  시연/week2/프로세스.js
Labels: 2주차, 스택/큐

#6 [week 2] 주간 결산_박소영
  소영/week2/기능개발.js
  소영/week2/프로세스.js
Labels: 2주차, 스택/큐

#5 [week 2] 주간 결산_이정우
  정우/week2/기능 개발.js
  정우/week2/프로세스.js
Labels: 2주차, 스택/큐

#8 2주차 스택/큐 과제 문제풀이
  유진/week2/functionDevelopment.js
  유진/week2/process.js
Labels: 2주차, 스택/큐

#12 [week 3] Heap(힙)_나유진
  유진/week3/더맵게.js
  유진/week3/이중우선순위큐.js
Labels: 3주차, 힙

#11 [week 3] Heap(힙)_이정우
  정우/week3/더 맵게.js
  정우/week3/이중우선순위큐.js
Labels: 3주차, 힙

#9 [week 3] Heap(힙)_이시연
  시연/week3/더맵게.js
  시연/week3/이중우선순위큐.js
Labels: 3주차, 힙

#10 [week 3] Heap(힙)_박소영
  소영/week3/더맵게.js
  소영/week3/이중우선순위큐.js
Labels: 3주차, 힙

#14 [week4] Hash(해시)_이시연
  시연/week4/완주하지못한선수.js
  시연/week4/전화번호목록.js
Labels: 4주차, 해시

#15 [week 4] Hash(해시)_박소영
  소영/week4/완주하지 못한 선수.js
  소영/week4/전화번호 목록.js
Labels: 4주차, 해시

#16 [week4] Hash(해시)_나유진
  유진/week4/완주하지못한선수.js
  유진/week4/전화번호목록.js
Labels: 4주차, 해시
